service: jamquery-api

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-webpack

package:
  individually: true

# custom configurations
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  jamquery-list:
    handler: jamquery.list
    events:
      - http:
          path: jamquery/{keyword}
          method: get
          request:
            parameters:
              paths:
                keyword: true
  add-new-jamquery:
    handler: jamquery.add
    events:
      - http:
          path: jamquery
          method: post
          